main: ResetChest\Main
version: "1.3"
author: SavionLegendZzz
api: [1.0.0]
load: POSTWORLD
commands:
 ResetChest:
  permission: rc.command
  description: ResetChest Main Command
  usage: /ResetChest <add|remove|reload|reset>
permissions:
 rc.*:
  default: op
  description: Main permission
  children:
   rc.command.*:
    default: op
    description: use commands
