name: HungerGames
main: HG\Main
version: "1.6"
api: [1.0.0]
load: POSTWORLD
soft-depend: "LevelChat, KillRate, MSpawns"
depend: "ResetChest"
author: SavionLegendZzz, and MinecrafterPH
commands:
 HungerGames:
  alias:
   hg:
  permission: hg.command.hg
  description: HungerGames Plugin Main Command
  usage: /HungerGames <|set<sign number>|example </hungergames set2>|remove|start|help>
 lobby:
  permission: hg.command.lobby
  description: HungerGames Lobby Command
  usage: /lobby <telports you back to the lobby>
permissions:
 hg.*:
  description: 
  default: op
  children:
   hg.command.*:
    description: 
    default: op
    children:
     hg.command.lobby:
      description: HungerGames Lobby Command
      default: true
     hg.command.set:
      description: set the status sign
      default: op
   hg.touch.startgame:
    description: 
    default: true
