name: HungerGames
main: HG\Main
version: "1.2"
api: [1.0.0]
load: POSTWORLD
author: a k i d
commands:
 hg:
  permission: hg.command.hg
  description: Commands /hg set|remove|stats 
  usage: /hg <set|remove|stats>
 lobby:
  permission: hg.command.lobby
  description: back to lobby
  usage: /lobby
permissions:
 hg.*:
  description: the main permission
  default: op
  children:
   hg.command.*:
    description: use commands in plugin
    default: op
    children:
     hg.command.lobby:
      description: back to lobby
      default: true
     hg.command.fsg:
      description: set SurvivalGame
      default: op
   hg.touch.startgame:
    description: click the sign and join the game
    default: true
